#
# Frigidaire FFAD7033R1 70-pint dehumidifier on a TP-Link Smart Wifi Plug Mini
#
# This dehumidifier is fast, less noisy than most and will auto-restart to its
# last condition in case of a power outage. This is great since we'll be
# controlling it with a smart power outlet. Its humistat is not used however:
# the device is run in continuous mode with humidity monitored by sensors
# throughout the dwelling. Automations take care of turning it on or off based
# on custom minimum and maximum humidity levels.
#
# @see /automations/devices/dehumidifier_on.yaml
# @see /automations/devices/dehumidifier_off.yaml
#
# @link http://www.dehumidifierbuyersguide.com/frigidaire-ffad7033r1-review/
# @link https://home-assistant.io/components/switch.tplink/
#
- platform: tplink
  name: Dehumidifier
  host: !secret tplink_dehumidifier_host
