#
# Nanoleaf Aurora loaded effect
#
# @see /appdaemon/dashboards/Switchboard.dash
# @see /customize.yaml
#
- platform: template
  sensors:
    aurora_effect_loaded:
      friendly_name: Aurora Effect Loaded
      value_template: >-
        {% if is_state('light.aurora', 'on') and state_attr('light.aurora', 'effect') != None %}
          {{ state_attr('light.aurora', 'effect') }}
        {% endif %}


#
# Bed glow lights loaded effect
#
# @see /appdaemon/dashboards/Switchboard.dash
# @see /customize.yaml
#
- platform: template
  sensors:
    bed_effect_loaded:
      friendly_name: Bed Effect Loaded
      value_template: >-
        {% if is_state('group.bed_lights', 'on') %}
          {{ states('variable.bed_effect') }}
        {% endif %}


#
# Ceiling wash lights loaded effect
#
# @see /appdaemon/dashboards/Switchboard.dash
# @see /customize.yaml
#
- platform: template
  sensors:
    ceiling_effect_loaded:
      friendly_name: Ceiling Effect Loaded
      value_template: >-
        {% if is_state('group.ceiling_lights', 'on') %}
          {{ states('variable.ceiling_effect') }}
        {% endif %}


#
# Lightpack TV backlight loaded effect
#
# @see /appdaemon/dashboards/Switchboard.dash
# @see /customize.yaml
#
- platform: template
  sensors:
    lightpack_effect_loaded:
      friendly_name: Lightpack Effect Loaded
      value_template: >-
        {% if is_state('light.lightpack', 'on') %}
          {{ states('variable.lightpack_effect') }}
        {% endif %}
