#
# Horizontal lines, for cosmetic separation of sensors in the UI.
#
# Actual styling is done in "customize" files.
#
# @see /customize.yaml
# @see /customize_glob.yaml
# @see /www/custom_ui/state-card-hline.html
# @see /www/custom_ui/state-card-hline_es5.html
#
# @link https://github.com/covrig/homeassistant-hline
#
- platform: template
  sensors:
    hline_dashed:
      value_template: hline

    hline_dashed_2:
      value_template: hline


#
# Current modes
#
# @see /appdaemon/dashboards/Switchboard.dash
#
- platform: template
  sensors:
    modes_friendly:
      friendly_name: Mode
      icon_template: mdi:emoticon-happy
      value_template: >-
        {% set counter = 0 %}
        {% set modes = '' %}

        {% if is_state('input_boolean.nap_mode', 'on') %}
          {% set modes = modes + '+ Nap ' %}
          {% set counter = counter + 1 %}
        {% endif %}

        {% if is_state('input_boolean.night_mode', 'on') %}
          {% set modes = modes + '+ Night ' %}
          {% set counter = counter + 1 %}
        {% endif %}

        {% if is_state('input_boolean.quiet_mode', 'on') %}
          {% set modes = modes + '+ Quiet ' %}
          {% set counter = counter + 1 %}
        {% endif %}

        {% if is_state('input_boolean.scene_mode', 'on') %}
          {% set modes = modes + '+ Scene ' %}
          {% set counter = counter + 1 %}
        {% endif %}

        {% if modes == '' %}
          {% set modes = 'Regular ' %}
          {% set counter = counter + 1 %}
        {% endif %}

        {{ modes.lstrip('+') }}mode
        {%- if counter > 1 -%}
          s
        {% endif %}


#
# Samsung SyncThru Laser Printer (now HP)
#
# The drum reports on its remaining percentage, while the toner also returns
# its print count, allowing for more accurate calculations.
#
# In order to keep configuration and logic separate, values for
# `printer_drum_capacity` and `printer_toner_capacity` are integers set in the
# secrets file.
#
# Do note that the `resource` parameter must not have a trailing slash,
# otherwise the sensor will fail.
#
# @see `secrets-dummy.yaml`
#
# @link https://www.home-assistant.io/components/sensor.syncthru/
#
- platform: syncthru
  resource: !secret syncthru_resource
  name: Printer
  monitored_conditions:
    - drum_black
    - toner_black

- platform: template
  sensors:
    printer_drum_capacity:
      friendly_name: Drum Capacity
      icon_template: mdi:printer
      unit_of_measurement: 'pages'
      value_template: !secret printer_drum_capacity

    printer_drum_remain:
      friendly_name: Drum Remaining
      icon_template: mdi:printer
      unit_of_measurement: 'pages'
      value_template: >-
        {% set capacity = states('sensor.printer_drum_capacity') | int(-1) %}
        {% set drum = states('sensor.printer_drum_black') | int(-1) %}

        {% if capacity > 0 and drum >= 0 %}
          {{ (capacity * drum / 100) | round }}
        {% else %}
          unknown
        {% endif %}

    printer_drum_use:
      friendly_name: Drum Use
      icon_template: mdi:printer
      unit_of_measurement: 'pages'
      value_template: >-
        {% set capacity = states('sensor.printer_drum_capacity') | int(-1) %}
        {% set drum = states('sensor.printer_drum_black') | int(-1) %}

        {% if capacity > 0 and drum >= 0 %}
          {{ (capacity * (100 - drum) / 100) | round }}
        {% else %}
          unknown
        {% endif %}

    printer_toner_capacity:
      friendly_name: Toner Capacity
      icon_template: mdi:printer
      unit_of_measurement: 'pages'
      value_template: !secret printer_toner_capacity

    printer_toner_remain:
      friendly_name: Toner Remaining
      icon_template: mdi:printer
      unit_of_measurement: 'pages'
      value_template: >-
        {% set capacity = states('sensor.printer_toner_capacity') | int(-1) %}
        {% set toner = state_attr('sensor.printer_toner_black', 'cnt') | int(-1) %}

        {% if capacity > 0 and toner >= 0 %}
          {{ capacity - toner }}
        {% else %}
          unknown
        {% endif %}

    printer_toner_use:
      friendly_name: Toner Use
      icon_template: mdi:printer
      unit_of_measurement: 'pages'
      value_template: >-
        {% set toner = state_attr('sensor.printer_toner_black', 'cnt') | int(-1) %}

        {% if toner >= 0 %}
          {{ toner }}
        {% else %}
          unknown
        {% endif %}


#
# Random positive quotes, to brighten up the day!
#
# @link http://www.lifestalker.com/2017/04/four-word-quotes.html
#
- platform: template
  sensors:
    good_vibes:
      friendly_name: Good Vibes
      icon_template: mdi:emoticon-happy
      entity_id:
        - sensor.time
      value_template: >-
        {% set vibes = [
          "Be great.",
          "Be happy!",
          "Be in the now.",
          "Be the hero.",
          "Begin anywhere.",
          "Compliment someone today.",
          "Do something great.",
          "Don't worry, be happy.",
          "Dream big dreams",
          "Enjoy life!",
          "Enjoy the little things.",
          "Everybody loves you!",
          "Follow your own star.",
          "Grab life by the balls.",
          "Hello gorgeous!",
          "It's never too late.",
          "Just go for it.",
          "Just ship it.",
          "Live with passion.",
          "Love yourself.",
          "Never doubt your instinct.",
          "People envy you",
          "People want to be you",
          "Pick one thing and do it.",
          "Ride like the wind.",
          "Seize the day!",
          "Start something.",
          "Think big!",
          "Think less. Feel more.",
          "Work hard, stay humble.",
          "You are a kind soul.",
          "You are a winner!",
          "You are an inspiration.",
          "You are awesome!",
          "You are fabulous!",
          "You are the best!",
          "You are the champion...",
          "You are the most awesome!",
          "You are your choices.",
          "You can do great things!",
          "You can move mountains",
          "You live only once.",
          "You look delicious!",
          "You make people happy.",
          "Your time is now.",
        ] %}
        {% set index = range(0, vibes|length - 1) | random %}

        {{ vibes[index] }}
